pipeline {
    agent {
        docker {
            image 'ubuntu:22.04'
            args '-v /var/run/docker.sock:/var/run/docker.sock -u root'
        }
    }

    environment {
        AWS_REGION       = 'ap-south-1'
        AWS_ACCOUNT_ID   =  credentials('AWS_ACCOUNT_ID')
        ECR_REGISTRY     =  credentials('ECR_REGISTRY')

        BACKEND_IMAGE    = 'ecolibirium-backend'
        FRONTEND_IMAGE   = 'ecolibirium-frontend'
        IMAGE_TAG        = "${env.BUILD_NUMBER}"

        CLUSTER_NAME     = 'ecolibirium-eks-cluster'
    }

    stages {

        stage('Setup Tools') {
            steps {
                sh '''
                    apt-get update -y
                    apt-get install -y curl unzip docker.io
                '''
            }
        }

        stage('Build & Push to ECR') {
            parallel {
                stage('Backend') {
                    steps {
                        script {
                            docker.withRegistry("https://${ECR_REGISTRY}", "ecr:${AWS_REGION}:aws-credentials") {
                                def img = docker.build("${ECR_REGISTRY}/${BACKEND_IMAGE}:${IMAGE_TAG}", "./Application/FlaskApp/Backend")
                                img.push()
                                img.push('latest')
                            }
                        }
                    }
                }
                stage('Frontend') {
                    steps {
                        script {
                            docker.withRegistry("https://${ECR_REGISTRY}", "ecr:${AWS_REGION}:aws-credentials") {
                                def img = docker.build("${ECR_REGISTRY}/${FRONTEND_IMAGE}:${IMAGE_TAG}", "./Application/FlaskApp/Frontend")
                                img.push()
                                img.push('latest')
                            }
                        }
                    }
                }
            }
        }

    }
}
