pipeline {
    agent {
        docker { 
            image 'hashicorp/terraform:1.14.7' 
            args  '--entrypoint='
        }
    }
    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Select the action to perform on the S3 bucket')
    }
    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION    = 'ap-south-1' 
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Terraform Init') {
            steps {
                dir('Terraform'){
                    sh 'terraform init'
                }
            }
        }
        stage('Terraform Plan') {
            steps {
                dir('Terraform'){
                    sh 'terraform plan -out=tfplan'
                }
            }
        }
        stage('Manual Approval') {
            agent none 
            steps {
                input message: "Are you sure you want to ${params.ACTION} the resources?", ok: "Proceed with ${params.ACTION}"
            }
        }
        stage('Terraform Action') {
            steps {
                dir('Terraform') {
                    script {
                        if (params.ACTION == 'destroy') {
                            sh 'terraform apply "destroyplan"'
                        } else {
                            sh 'terraform apply "tfplan"'
                        }
                    }
                }       
            }
        }
    }
}    
