pipeline {
    agent {
        docker { 
            image 'hashicorp/terraform:1.14.7' 
            args  '--entrypoint='
        }
    }
    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION    = 'ap-south-1' 
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Terraform Init') {
            steps {
                dir('Terraform'){
                    sh 'terraform init'
                }
            }
        }
        stage('Terraform Plan') {
            steps {
                dir('Terraform'){
                    sh 'terraform plan -out=tfplan'
                }
            }
        }
        stage('Manual Approval') {
            agent none 
            steps {
                script {
                    def userInput = input(
                        id: 'userInput',
                        message: 'Review the Terraform Plan. Do you want to apply these changes?',
                        parameters: [
                            [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Terraform Changes', name: 'confirm']
                        ]
                    )
                }
            }
        }
        stage('Terraform Apply') {
            steps {
                dir('Terraform'){
                    sh 'terraform apply -auto-approve tfplan'
                }
            }
        }
    }
}
