apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment-eco-backend-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: assignment-eco-backend
  template:
    metadata:
      labels:
        app: assignment-eco-backend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000

      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}

          ports:
            - containerPort: 5000

          envFrom:
            - configMapRef:
                name: assignment-eco-backend-config
            - secretRef:
                name: assignment-eco-backend-secret

          livenessProbe:
            httpGet:
              path: /health/live
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health/ready
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3

          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
