apiVersion: v1
kind: Secret
metadata:
  name: assignment-eco-backend-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.backend.secret.DB_PASSWORD | quote }}
  SECRET_KEY:  {{ .Values.backend.secret.SECRET_KEY  | quote }}
  API_KEY:     {{ .Values.backend.secret.API_KEY     | quote }}
  JWT_SECRET:  {{ .Values.backend.secret.JWT_SECRET  | quote }}
