apiVersion: v1
kind: Service
metadata:
  name: assignment-eco-backend-svc
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: assignment-eco-backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 5000
      protocol: TCP
