apiVersion: v1
kind: Service
metadata:
  name: assignment-eco-frontend-svc
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: assignment-eco-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 8080
      protocol: TCP
